services:
  h2:
    image: 'oscarfonts/h2'
    ports:
      - '8082:8082'
      - '9092:9092'
    volumes:
      - ./data:/opt/h2-data
    environment:
      - H2_OPTIONS='-ifNotExists -web -webAllowOthers -webPort 8082 -tcp -tcpAllowOthers -tcpPort 9092'
